2025-02-20 12:45:43,605 ERROR frappe Failed to run after request hook
Site: helpdesk-mtrh.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 69, in _get_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 108, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 370, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/utils.py", line 517, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 117, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined
2025-02-20 12:46:16,566 ERROR frappe New Exception collected with id: 2025-02-20 12:46:16.546483-10.30.166.51-8ff
Site: helpdesk-mtrh.com
Form Dict: {}
2025-02-20 12:46:16,569 ERROR frappe Failed to run after request hook
Site: helpdesk-mtrh.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 69, in _get_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 108, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 370, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/utils.py", line 517, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 117, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1512, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1481, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abigael/frappe-bench/apps/help_desk/help_desk/hooks.py", line 129, in <module>
    "validate":help_desk.permissions.allow_file_upload
NameError: name 'help_desk' is not defined
